### ISSUE TITLE
ImportError: No module named 'deoplete.sources'

### ISSUE THREAD

**Issue by zhou13** [zchee/deoplete-zsh#1]
It seems that this plugin won't work with last `deoplete.nvim`.  I keep getting error

```
ImportError: No module named 'deoplete.sources'
```

**Comment by Shougo** [comment]
It is deoplete-zsh problem.
It should be fixed...

**Comment by zchee** [comment]
@zhou13 Sorry! Fixed now :)
https://github.com/zchee/deoplete-zsh/commit/86d366959f110000b4d836e0f2edc3986fb02a2d
