### ISSUE TITLE
deoplete-zsh doesn't work in .sh file

### ISSUE THREAD

**Issue by voldikss** [zchee/deoplete-zsh#11]
Hi @zchee , thank you for your implement! It works pretty well in `.zsh` file, but not in `.sh` file.
Notice that `zsh` is compatible with `sh`, can this plugin also works `.sh` file?

**Comment by Shougo** [comment]
It is already supported.

```vim
call deoplete#custom#source('zsh', 'filetypes', ['zsh', 'sh'])
```
