### ISSUE TITLE
[ help ] how to install with vim-plug

### ISSUE THREAD

**Issue by nerd190** [zchee/deoplete-zsh#17]
Hi, I use vim-plug, how would I install this? I only ask as there are no installation instructions and it contains a python dependency, so I dont think (could be wrong!) that a simple `zplug 'deoplete-plugins/deoplete-zsh'` will work, thank you!

**Comment by Shougo** [comment]
You need to install it as Vim plugin.
`zplug` is wrong.

**Comment by Shougo** [comment]
`Plug 'deoplete-plugins/deoplete-zsh'`
