### ISSUE TITLE
deopleteで補完が出ない

### ISSUE THREAD

**Issue by ghost** [zchee/deoplete-zsh#18]
dein.vim
deoplete.nvim
deol.nvim
deoplete-zsh
で再現しました
以下最小構成です
```
[[plugins]]
repo = "Shougo/deol.nvim"

[[plugins]]
repo = 'deoplete-plugins/deoplete-zsh'

[[plugins]]
repo = 'Shougo/deoplete.nvim'
hook_source = '''
  let g:deoplete#enable_at_startup = 1
  call deoplete#custom#option({
    \ 'nofile_complete_filetypes': ['zsh'],
    \ })
  inoremap <expr><Tab> pumvisible() ? "\<C-n>" : "\<Tab>"
  inoremap <expr><S-Tab> pumvisible() ? "\<UP>" : "\<S-Tab>"
'''
```

**Comment by Shougo** [comment]
```vim
set rtp+=~/work/deoplete.nvim/
set rtp+=~/work/nvim-yarp
set rtp+=~/work/vim-hug-neovim-rpc
set rtp+=~/work/deol.nvim
set rtp+=~/work/deoplete-zsh

let g:deoplete#enable_at_startup = 1

call deoplete#custom#option({
    \ 'nofile_complete_filetypes': ['zsh'],
    \ })
inoremap <expr><Tab> pumvisible() ? "\<C-n>" : "\<Tab>"
inoremap <expr><S-Tab> pumvisible() ? "\<UP>" : "\<S-Tab>"

set shell=zsh

tnoremap   <ESC>         <C-\><C-n>

autocmd FileType deol nmap <buffer> i <Plug>(deol_edit)
```

これが本当の最小構成です。補完はちゃんと出ます。
Vim 起動してからの再現手順をちゃんと示してください。

* `vim`
* `:Deol`
* `<ESC>i`
* `ls` と入力する

**Comment by Shougo** [comment]
![スクリーンショット_2021-05-17_12-32-23](https://user-images.githubusercontent.com/41495/118429163-00739f00-b70c-11eb-87d2-d38532df1d86.png)

なぜ私の手元では動作しているのでしょうか？？

**Comment by Shougo** [comment]
> deopleteで補完が出ない

fuzzy すぎます。こういう手順をして補完を出したらこうなるとしてください。
我々はエスパーではありません。

**Comment by Shougo** [comment]
![スクリーンショット_2021-05-17_12-35-47](https://user-images.githubusercontent.com/41495/118429383-8abc0300-b70c-11eb-99f7-af98a10275f6.png)

**Comment by Shougo** [comment]
> 以下最小構成です

これは最小構成になっていないので、私のものと比較をお願いします。
最小構成にプラグインマネージャーを使うべきではありません。
そのうえ、この vimrc はそのまま実行可能でありません。

**Comment by ghost** [comment]
いろいろと不十分な状態でissueを建ててしまったこと申し訳ありません。issueを建てることが初めてだったので次回から注意します。ありがとうございました

**Comment by Shougo** [comment]
最小構成で動作したとのことでプラグイン側の問題ではないのでクローズします。

> いろいろと不十分な状態でissueを建ててしまったこと申し訳ありません。issueを建てることが初めてだったので次回から注意します。ありがとうございました

誰でも最初から完璧な報告ができるわけではありません。私も昔はひどいものでした。
しかし問題解決のためには誰でも再現が可能な報告を行う必要があります。
これは意地悪をしているわけではなく、私は問題を本気で解決したいと思っているからそこまで言います。
他の人の場合はそこまでしなくて、単純に報告を無視するという対応の仕方のほうが残念ながら多いです。
そのほうが手間はかかりませんからね。
