### ISSUE TITLE
configurable .zcompdump filepath

### ISSUE THREAD

**Issue by zchee** [zchee/deoplete-zsh#3]
Currently, hardcoded `compinit -d ~/.zcompdump_capture`, it will create `.zcompdump` cache to user home directory.
But, I would like to keep clearly the home directory as much as possible.
I think under the `$XDG_CACHE_HOME` is better.

**Comment by ghost** [comment]
What about `$XDG_CACHE_HOME/deoplete/zcompdump` ?

---

候補として `$XDG_CACHE_HOME/deoplete/zcompdump` はどうですか？
また、環境変数でユーザーが設定できるようにしたらいいとおもいます。

**Comment by zchee** [comment]
@39e ありがとうございます！
$XDG_CACHE_HOME/deoplete/jediとか他で切ってるのでzshを間に入れようか迷っていますがいかがでしょう？
ちなみにどんな環境変数がお好みですか？

**Comment by ghost** [comment]
> 他で切ってる

`$XDG_CACHE_HOME/deoplete/zsh/compdump` みたいな感じですか？

> 環境変数

`$DEOPLETE_ZSH_CACHE_DIR/compdump` みたいな形はいかがですか？

**Comment by zchee** [comment]
@39e LGTMすぎるのでそちらで実装します！！！
